<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Configurations>Debug;Release;Production</Configurations>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Class1.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Auth0Demo.Application\Auth0Demo.Application.csproj" />
    <ProjectReference Include="..\Auth0Demo.Domain\Auth0Demo.Domain.csproj" />
  </ItemGroup>

</Project>
